[package]
name = "hacker-news-iced"
version = "0.1.0"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# iced = { version = "0.12", features = ["lazy", "tokio", "advanced"] }
iced = { version = "0.13", features = [
    "lazy",
    "tokio",
    "advanced",
    "auto-detect-theme",
    "image",
] }

hacker-news-api.workspace = true
html-sanitizer.workspace = true
log.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
tokio.workspace = true

open = "5"
either = "1"
app_dirs2 = "2"
rmp-serde = "1.3"
