[workspace]
resolver = "2"
members = [
  "hacker-news-api",
  "hacker-news-config",
  "hacker-news-gpui",
  "hacker-news-iced",
  "hacker-news-search",
  "hacker-news-tui",
  "html-sanitizer",
  "platform-settings",
]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
app_dirs2 = "2"
chrono = "0.4"
chrono-tz = "0.10"
futures = "0.3"
gio = "0.22"
glib = "0.22"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }

hacker-news-api.path = "hacker-news-api"
hacker-news-config.path = "hacker-news-config"
hacker-news-search.path = "hacker-news-search"
html-sanitizer.path = "html-sanitizer"
