[package]
name = "hacker-news-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
authors = ["Darrell Roberts"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tokio = { version = "1", features = ["macros", "sync"] }
futures = "0.3"
