[package]
name = "hacker-news-api"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
anyhow.workspace = true
bytes = "1"
futures.workspace = true
log.workspace = true
reqwest = {
  version = "0.12",
  features = [
    "gzip",
    "json",
    "rustls-tls",
    "stream",
  ]
}
serde.workspace = true
serde_json.workspace = true
thiserror = "2"
tokio = { version = "1", features = ["macros", "sync"] }
tracing = { version = "0.1", optional = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
trace = ["tracing"]
