name: Create Release

on:
  push:
    tags:
      - "v*" # Triggers on tags starting with 'v'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build bundle
        run: make bundle-mac

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/Hacker News.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
