name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup glib
        run: sudo apt install libglib2.0-dev
      - name: Build
        run: cargo build --bin hacker-news-reader
      - name: Run clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test
